[2024-02-03T03:14:31.868+0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iris_score.get_data manual__2024-02-02T23:14:29.313962+00:00 [queued]>
[2024-02-03T03:14:31.871+0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iris_score.get_data manual__2024-02-02T23:14:29.313962+00:00 [queued]>
[2024-02-03T03:14:31.871+0400] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-03T03:14:31.881+0400] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): get_data> on 2024-02-02 23:14:29.313962+00:00
[2024-02-03T03:14:31.883+0400] {standard_task_runner.py:60} INFO - Started process 25779 to run task
[2024-02-03T03:14:31.886+0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'iris_score', 'get_data', 'manual__2024-02-02T23:14:29.313962+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/iris_score.py', '--cfg-path', '/tmp/tmpqu899ycm']
[2024-02-03T03:14:31.887+0400] {standard_task_runner.py:88} INFO - Job 18: Subtask get_data
[2024-02-03T03:14:31.914+0400] {task_command.py:423} INFO - Running <TaskInstance: iris_score.get_data manual__2024-02-02T23:14:29.313962+00:00 [running]> on host WIN-IO5IBOGGQDO.localdomain
[2024-02-03T03:14:31.952+0400] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='iris_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T23:14:29.313962+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-02T23:14:29.313962+00:00'
[2024-02-03T03:14:31.953+0400] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-03T03:14:31.954+0400] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/reurairin/projects/urfu/urfu_3s_mlops-3/scripts/get_data.py']
[2024-02-03T03:14:31.959+0400] {subprocess.py:86} INFO - Output:
[2024-02-03T03:15:07.625+0400] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 25779. PIDs of all processes in the group: [25780, 25779]
[2024-02-03T03:15:07.626+0400] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 25779
[2024-02-03T03:15:07.626+0400] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-03T03:15:07.626+0400] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-02-03T03:15:07.632+0400] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reurairin/projects/urfu/urfu_3s_mlops-3/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/reurairin/projects/urfu/urfu_3s_mlops-3/env/lib/python3.10/site-packages/airflow/operators/bash.py", line 203, in execute
    result = self.subprocess_hook.run_command(
  File "/home/reurairin/projects/urfu/urfu_3s_mlops-3/env/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/reurairin/projects/urfu/urfu_3s_mlops-3/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-02-03T03:15:07.635+0400] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=iris_score, task_id=get_data, execution_date=20240202T231429, start_date=20240202T231431, end_date=20240202T231507
[2024-02-03T03:15:07.644+0400] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task get_data (Task received SIGTERM signal; 25779)
[2024-02-03T03:15:07.652+0400] {process_utils.py:79} INFO - Process psutil.Process(pid=25779, status='terminated', exitcode=1, started='03:14:31') (25779) terminated with exit code 1
[2024-02-03T03:15:07.653+0400] {process_utils.py:79} INFO - Process psutil.Process(pid=25780, status='terminated', started='03:14:31') (25780) terminated with exit code None
